apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-runtime-processor
  labels:
    app: streaming-runtime-processor
    component: streaming-runtime-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-runtime-processor
  template:
    metadata:
      labels:
        app: streaming-runtime-processor
        component: streaming-runtime-processor
    spec:
      containers:
        - name: multibinder-grpc
          image: ghcr.io/vmware-tanzu/streaming-runtimes/sql-aggregator:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_FUNCTION_GRPC_PORT
              value: "55554"
            - name: SPRING_CLOUD_FUNCTION_GRPC_SERVER
              value: "false"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10